[workspace]
members = ["plugin_test"]

[package]
name = "servers"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.56"
clap = { version = "3.1.18", features = ["derive"] }
libloading = "0.7.3"
log = { version = "0.4.17", features = ["release_max_level_info", "max_level_trace"] }
simple_logger = { version = "2.1.0", default-features = false, features = ["colors"] }
tokio = { version = "1.19.0", features = ["rt-multi-thread", "macros"] }
