[workspace]
members = ["plugin_test"]
resolver = "2"

[package]
name = "servers"
description = "Simple TCP server for clients written in Rust with plugins support."
version = "0.3.0"
license = "MIT"
authors = ["MedzikUser <medzik@duck.com>"]
homepage = "https://github.com/MedzikUser/servers"
repository = "https://github.com/MedzikUser/servers.git"
edition = "2021"

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1

[dependencies]
anyhow = "1.0.58"
async-trait = "0.1.56"
better-panic = "0.3.0"
lazy_static = "1.4.0"
libloading = "0.7.3"
tokio-tungstenite = "0.17.2"
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
tungstenite = "0.17.3"
clap = { version = "3.2.16", features = ["derive"] }
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
tokio = { version = "1.20.1", features = ["rt-multi-thread", "macros", "net"] }
