[workspace]
members = ["plugin_test"]

[package]
name = "servers"
description = "Simple TCP server for clients written in Rust with plugins support"
version = "0.2.0"
license = "MIT"
authors = ["MedzikUser <nivua1fn@duck.com>"]
homepage = "https://github.com/MedzikUser/servers"
repository = "https://github.com/MedzikUser/servers.git"
edition = "2021"

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1

[dependencies]
anyhow = "1.0.58"
async-trait = "0.1.56"
better-panic = "0.3.0"
libloading = "0.7.3"
simplelog = "0.12.0"
tokio-tungstenite = "0.17.1"
tungstenite = "0.17.2"
clap = { version = "3.2.8", features = ["derive"] }
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
log = { version = "0.4.17", features = ["release_max_level_info", "max_level_debug"] }
tokio = { version = "1.19.2", features = ["rt-multi-thread", "macros", "net"] }
